name: Build my package

on:
  push:
    branches: [ main ]

jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm cache clean --force
      - run: npm install
      - run: npm run build --if-present
